// Kimi_Agent_资产组合压力测试Vue v2/app/src/components/ScrollReveal.vue
<template>
  <div ref="el" class="scroll-reveal" :class="$props.class" :style="style">
    <slot />
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, computed } from 'vue'
import gsap from 'gsap'
import { ScrollTrigger } from 'gsap/ScrollTrigger'

gsap.registerPlugin(ScrollTrigger)

const props = defineProps<{
  class?: string
  delay?: number
  direction?: 'up' | 'left'
  duration?: number
  style?: Record<string, string>
}>()

const el = ref<HTMLDivElement>()

const style = computed(() => ({
  opacity: '0',
  transform: props.direction === 'left' ? 'translateX(-10px)' : 'translateY(30px)',
  ...props.style,
}))

onMounted(() => {
  if (!el.value) return
  gsap.to(el.value, {
    opacity: 1,
    x: 0,
    y: 0,
    duration: props.duration ?? 0.8,
    delay: props.delay ?? 0,
    ease: 'cubic-bezier(0.22, 1, 0.36, 1)',
    scrollTrigger: {
      trigger: el.value,
      start: 'top 85%',
      toggleActions: 'play none none none',
    },
  })
})
</script>

// prototypes/investment-ui/app/src/components/ScrollReveal.tsx
import { useRef, useEffect, type ReactNode } from 'react'
import gsap from 'gsap'
import { ScrollTrigger } from 'gsap/ScrollTrigger'

gsap.registerPlugin(ScrollTrigger)

interface ScrollRevealProps {
  children: ReactNode
  className?: string
  delay?: number
  direction?: 'up' | 'left'
  duration?: number
  stagger?: number
  style?: React.CSSProperties
}

export default function ScrollReveal({
  children,
  className = '',
  delay = 0,
  direction = 'up',
  duration = 0.8,
  style,
}: ScrollRevealProps) {
  const ref = useRef<HTMLDivElement>(null)

  useEffect(() => {
    const el = ref.current
    if (!el) return

    const fromX = direction === 'left' ? -10 : 0
    const fromY = direction === 'up' ? 30 : 0

    gsap.fromTo(
      el,
      { opacity: 0, x: fromX, y: fromY },
      {
        opacity: 1,
        x: 0,
        y: 0,
        duration,
        delay,
        ease: 'cubic-bezier(0.22, 1, 0.36, 1)',
        scrollTrigger: {
          trigger: el,
          start: 'top 85%',
          toggleActions: 'play none none none',
        },
      }
    )

    return () => {
      ScrollTrigger.getAll().forEach((t) => {
        if (t.trigger === el) t.kill()
      })
    }
  }, [delay, direction, duration])

  return (
    <div ref={ref} className={className} style={{ opacity: 0, ...style }}>
      {children}
    </div>
  )
}

interface StaggerContainerProps {
  children: ReactNode
  className?: string
  staggerDelay?: number
  childSelector?: string
}

export function StaggerContainer({
  children,
  className = '',
  staggerDelay = 0.1,
  childSelector = '.stagger-item',
}: StaggerContainerProps) {
  const ref = useRef<HTMLDivElement>(null)

  useEffect(() => {
    const el = ref.current
    if (!el) return

    const children = el.querySelectorAll(childSelector)
    if (children.length === 0) return

    gsap.fromTo(
      children,
      { opacity: 0, y: 30 },
      {
        opacity: 1,
        y: 0,
        duration: 0.8,
        stagger: staggerDelay,
        ease: 'cubic-bezier(0.22, 1, 0.36, 1)',
        scrollTrigger: {
          trigger: el,
          start: 'top 85%',
          toggleActions: 'play none none none',
        },
      }
    )

    return () => {
      ScrollTrigger.getAll().forEach((t) => {
        if (t.trigger === el) t.kill()
      })
    }
  }, [staggerDelay, childSelector])

  return (
    <div ref={ref} className={className}>
      {children}
    </div>
  )
}
